---
# this is the config that will be loaded as default by main.py
# Please follow the provided structure (this will ensuring all baseline follow
# a similar configuration structure and hence be easy to customise)

num_clients: 100
num_epochs: 5
batch_size_ratio: 0.2
clients_per_round: 10
learning_rate: 0.01
num_rounds: 1000
mu: 0.0

dataset:
  # dataset config
  similarity: 1.0 # similarity for sampling data
  batch_size_ratio: ${batch_size_ratio} # batch_size = batch_size_ratio * total_local_data_size
  val_split: 0.1

model:
  # model config
  _target_: scaffold.models.LogisticRegression
  num_classes: 47

strategy:
  _target_: scaffold.strategy.ScaffodStrategy # points to your strategy (either custom or exiting in Flower)
  # rest of strategy config
  fraction_fit: 0.00001 # because we want the number of clients to sample on each round to be solely defined by min_fit_clients
  fraction_evaluate: 0.0
  min_fit_clients: ${clients_per_round}
  min_available_clients: ${clients_per_round}
  min_evaluate_clients: 0

client:
  # client config

server_device: cpu

client_resources:
  num_cpus: 4
  num_gpus: 0.0