---
# this is the config that will be loaded as default by main.py
# Please follow the provided structure (this will ensuring all baseline follow
# a similar configuration structure and hence be easy to customise)

num_clients: 100
num_epochs: 10
batch_size_ratio: 0.2
clients_per_round: 20
learning_rate: 0.01
num_rounds: 1000
mu: 0.0
momentum: 0.0
weight_decay: 0.0
partitioning: "iid_noniid"
dataset_seed: 42
dataset_name: "emnist"

dataset:
  # dataset config
  _name: ${dataset_name}
  _partitioning: ${partitioning}
  seed: ${dataset_seed}
  similarity: 0.1 # similarity for sampling data
  batch_size_ratio: ${batch_size_ratio} # batch_size = batch_size_ratio * total_local_data_size
  val_split: 0.0

model:
  # model config
  _target_: scaffold.models.LogisticRegression
  num_classes: 47

strategy:
  _target_: flwr.server.strategy.FedAvg # points to your strategy (either custom or exiting in Flower)
  # rest of strategy config
  fraction_fit: 0.00001 # because we want the number of clients to sample on each round to be solely defined by min_fit_clients
  fraction_evaluate: 0.0
  min_fit_clients: ${clients_per_round}
  min_available_clients: ${clients_per_round}
  min_evaluate_clients: 0

client:
  # client config

server_device: cpu

client_resources:
  num_cpus: 4
  num_gpus: 0.0
